// @vitest-environment node
/**
 * Golden regression for PDF reflow: 22 real pages (make_golden.py) run through
 * the same pdf.js + reflow pipeline the app uses; the readable outline of each
 * result is compared with pdfReflowGolden.snap.md.
 *
 * Any change to a reflow rule shows up here as a reviewable text diff. When a
 * change is intended, regenerate and review the snapshot diff:
 *
 *   UPDATE_REFLOW_GOLDEN=1 pnpm test --run src/__tests__/utils/pdfReflowGolden.test.ts
 */
import { describe, expect, it } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';
import { extractPdfGraphics } from '@/utils/pdfReflowGraphics';
import { reflowPdfText, type PdfTextItem, type ReflowPage } from '@/utils/pdfReflow';
import { GOLDEN_PDFS } from '../fixtures/data/pdfReflowGoldenFixtures';

const root = path.resolve(__dirname, '../../../../../packages/foliate-js/node_modules/pdfjs-dist');
const SNAPSHOT = path.resolve(__dirname, 'pdfReflowGolden.snap.md');

interface PdfJs {
  OPS: Record<string, number>;
  getDocument: (options: Record<string, unknown>) => {
    promise: Promise<{
      getPage: (n: number) => Promise<{
        view: number[];
        getTextContent: () => Promise<{ items: Array<Record<string, unknown>> }>;
        getOperatorList: () => Promise<{
          fnArray: ArrayLike<number>;
          argsArray: ArrayLike<unknown>;
        }>;
      }>;
    }>;
  };
}

async function reflow(data: string): Promise<ReflowPage> {
  const pdfjs = (await import(
    '../../../../../packages/foliate-js/node_modules/pdfjs-dist/legacy/build/pdf.mjs'
  )) as unknown as PdfJs;
  const doc = await pdfjs.getDocument({
    data: new Uint8Array(Buffer.from(data, 'base64')),
    useSystemFonts: true,
    disableFontFace: true,
    cMapUrl: `${root}/cmaps/`,
    cMapPacked: true,
    standardFontDataUrl: `${root}/standard_fonts/`,
  }).promise;
  const page = await doc.getPage(1);
  const [x1, y1, x2, y2] = page.view as [number, number, number, number];
  const items: PdfTextItem[] = [];
  for (const item of (await page.getTextContent()).items) {
    if (typeof item['str'] !== 'string') continue;
    const t = item['transform'] as number[];
    items.push({
      str: item['str'],
      width: item['width'] as number,
      height: item['height'] as number,
      transform: [...t.slice(0, 4), t[4]! - x1, t[5]! - y1],
      hasEOL: item['hasEOL'] as boolean,
      dir: item['dir'] as string,
    });
  }
  const graphics = extractPdfGraphics(
    await page.getOperatorList(),
    pdfjs.OPS,
    [x1, y1],
    x2 - x1,
    y2 - y1,
  );
  return reflowPdfText(items, x2 - x1, y2 - y1, true, graphics);
}

/** Stable, human-readable outline: block kinds, text, table shape, figure
 * size rounded to 10pt, removed page numbers and warnings. */
function outline(page: ReflowPage): string {
  const lines: string[] = [];
  let lastTable = '';
  for (const block of page.blocks) {
    if (block.kind === 'cell' && block.table) {
      const t = block.table;
      const shape = `table ${t.rows}x${t.cols}`;
      if (shape !== lastTable) lines.push(`- ${shape}`);
      lastTable = shape;
      const flags = [
        t.header && 'header',
        t.numeric && 'num',
        t.rowSpan > 1 && `rs${t.rowSpan}`,
        t.colSpan > 1 && `cs${t.colSpan}`,
      ]
        .filter(Boolean)
        .join(',');
      lines.push(`  - [${t.row},${t.col}${flags ? ' ' + flags : ''}] ${block.text}`);
      continue;
    }
    lastTable = '';
    if (block.kind === 'figure' && block.figure) {
      const f = block.figure;
      const r = (n: number) => Math.round(n / 10) * 10;
      lines.push(`- figure ${r(f.x1 - f.x0)}x${r(f.y1 - f.y0)}`);
    } else {
      lines.push(`- ${block.kind}: ${block.text}`);
    }
  }
  if (page.removedPageNumbers.length)
    lines.push(`- removed page numbers: ${page.removedPageNumbers.join(', ')}`);
  for (const w of page.warnings) lines.push(`- warning: ${w}`);
  return lines.join('\n');
}

async function render(): Promise<string> {
  const parts = [
    '# PDF reflow golden outlines',
    '',
    'Generated by pdfReflowGolden.test.ts. Review diffs; do not hand-edit.',
    '',
  ];
  for (const [name, data] of Object.entries(GOLDEN_PDFS)) {
    parts.push(`## ${name}`, '', outline(await reflow(data)), '');
  }
  return parts.join('\n');
}

describe('PDF reflow golden pages', () => {
  it('matches the reviewed outline of every golden page', { timeout: 60000 }, async () => {
    const actual = await render();
    if (process.env['UPDATE_REFLOW_GOLDEN'] === '1' || !fs.existsSync(SNAPSHOT)) {
      fs.writeFileSync(SNAPSHOT, actual);
      if (process.env['UPDATE_REFLOW_GOLDEN'] !== '1')
        throw new Error(
          'pdfReflowGolden.snap.md was missing and has been written; review it and re-run.',
        );
      return;
    }
    const expected = fs.readFileSync(SNAPSHOT, 'utf8');
    if (actual !== expected) {
      // Name the pages that changed so the failure is readable on its own.
      const split = (s: string) =>
        Object.fromEntries(
          s
            .split(/^## /m)
            .slice(1)
            .map((sec) => [sec.split('\n')[0], sec]),
        );
      const a = split(actual);
      const e = split(expected);
      const changed = [...new Set([...Object.keys(a), ...Object.keys(e)])].filter(
        (k) => a[k] !== e[k],
      );
      expect.soft(changed, 'pages whose reflow output changed').toEqual([]);
    }
    expect(actual).toBe(expected);
  });

  // Known defects found by this golden set, recorded so the snapshot does not
  // silently bless them. Each is `it.fails`: when a fix lands the test starts
  // passing, vitest reports it, and it should become a normal `it`.
  describe('known reflow defects (expected to fail until fixed)', () => {
    const blocks = async (name: string) => (await reflow(GOLDEN_PDFS[name]!)).blocks;
    it('an unshaded code listing (code + trailing comment) is not a table', async () => {
      expect((await blocks('code-listing')).some((b) => b.kind === 'cell')).toBe(false);
    });
    it('list items stay separate blocks instead of one run-on paragraph', async () => {
      const list = (await blocks('bullets')).filter((b) => b.text.includes('•'));
      expect(list.length).toBeGreaterThanOrEqual(3);
    });
    it.fails('two columns are read column by column, not interleaved line by line', async () => {
      const first = (await blocks('two-column'))[0]!.text;
      expect(first).toContain('A mouse can fall from a building');
    });
    it('a rotated text watermark is dropped from the reading flow', async () => {
      expect(
        (await blocks('tilted-text-watermark')).some((b) => b.text.includes('SAMPLE COPY')),
      ).toBe(false);
    });
    it.fails('labels beside large figures are rebuilt as a 3x3 table', async () => {
      expect((await blocks('sparse-mixed-table')).filter((b) => b.kind === 'cell').length).toBe(9);
    });
  });

  it('every golden page reflows without throwing and keeps its text', async () => {
    for (const [name, data] of Object.entries(GOLDEN_PDFS)) {
      const page = await reflow(data);
      if (name === 'scan-no-text')
        expect(page.blocks.every((b) => b.kind !== 'paragraph')).toBe(true);
      else expect(page.blocks.length, name).toBeGreaterThan(0);
    }
  });
});
